### PR TITLE
Bump python versions fix 30

### PR DESCRIPTION
**Pull request by stevepiercy**
See #30

### CODE REVIEW

**Comment by fschulze** [comment]
There should be a changelog entry for dropping Python 3.4.

Should there be a major version bump for dropping Python 3.4?

**Comment by fschulze** [comment]
I would say remove your commits which attempt to fix coverage from this PR and make a new one for it.

**Comment by stevepiercy** [comment]
Can any y'all make sense of the [Travis error](https://travis-ci.org/github/Pylons/pyramid_zcml/jobs/671532661#L238)?

`No source for code: '/home/travis/build/Pylons/pyramid_zcml/pyramid_zcml/pyramid_zcml_tests_viewdecoratorapp_views_templates_foo_mak'.`

I'm just making wild guesses now.

It's fine to do a squash on the commits when merging.

**Comment by stevepiercy** [comment]
> There should be a changelog entry for dropping Python 3.4.
> 
> Should there be a major version bump for dropping Python 3.4?

Yes, yes, and done.

**Comment by fschulze** [comment]
I guess it will still fail to merge coverage in the end due to Python 2.7. I'd say go to 2.0.0 and drop Python 2.7 as well.

**Comment by stevepiercy** [comment]
I have no clue and my duckduckfu fails me.

I'll just drop Python 2.7. Incoming...

**Comment by fschulze** [comment]
If you get it working, I would prefer a rebase with all commits squashed except the doc changes. If you don't know how, then we should just squash merge.

**Comment by stevepiercy** [comment]
I give up. I tried dropping Python 2.7 and running coverage locally before in about a half-dozen permutations, but I clearly don't know what I'm doing. I pushed my last attempt.

**Comment by fschulze** [comment]
Phew, that *was* tricky.

**Comment by stevepiercy** [comment]
We might be able to use a `.coveragerc` to accomplish the same as the omit thing you put in there.

**Comment by stevepiercy** [comment]
Is there anything gained by moving commands from `tox.ini` into a new `.coveragerc`? I don't know enough to have an opinion.

I'm fine with this PR as is. Do we need an approval from @bertjwregeer or @tseaver?

**Comment by bertjwregeer** [comment]
We use `.coveragerc` in other projects.

**Comment by stevepiercy** [comment]
Done. One last review, and I think it's soup. @bertjwregeer @fschulze

**Comment by fschulze** [comment]
I redid the rebase you accidentally undid and cherry picked your last additional commit.

**Pull request merged**
