### PR TITLE
Update: tox/travis

### PR DESCRIPTION
**Pull request by bertjwregeer**
This is not entirely perfect yet, specifically at the moment test coverage does not work correctly due to:

```
pyramid_zcml/pyramid_zcml_tests_viewdecoratorapp_views_templates_foo_mak   NoSource: No source for code: '/Users/xistence/Projects/pyramid_zcml/pyramid_zcml/pyramid_zcml_tests_viewdecoratorapp_views_templates_foo_mak'.
```

I had to add `-i` to combine xml for it to even get to the stage of reporting coverage.

Currently a test file is also not fully covered:

```
pyramid_zcml/tests/routesapp/models.py                                         3      3     0%   1-4
```

This test run will still fail due to #8, but tox can now be re-run multiple times without the issues reported in #14.

### CODE REVIEW

**Comment by tseaver** [comment]
@bertjwregeer in order to get stuff passing to merge #16, I dropped 3.2 support.  I part-way added 3.5 support (tox but not Travis).  Can you merge / fixup?

**Comment by bertjwregeer** [comment]
I am currently over a satellite internet connection, and can't feasibly test locally (pulling down a tox env is painful).

**Comment by bertjwregeer** [comment]
@tseaver Seems like not everything is actually covered, also unless there is a way to get mako supported by coverage, we'll need to add an  -i to the XML command for it to ignore any missing commands.

**Comment by fschulze** [comment]
You might want to take a look at this: https://github.com/fschulze/pyramid_zcml/tree/tox-travis, but it doesn't merge coverage.

**Pull request closed without merging**
