### PR TITLE
use pylons-sphinx-themes package to render docs

### LINKED ISSUE #10: Update to use new pylons-sphinx-themes package
See https://github.com/Pylons/pylons-sphinx-themes

### PR DESCRIPTION
**Pull request by stevepiercy**
- modernize and make docs config more consistent with Pyramid
- Closes #10

### CODE REVIEW

**Comment by stevepiercy** [comment]
It won't build on Python 2.6. Anyone know why?

**Comment by stevepiercy** [comment]
This is why: https://github.com/Pylons/pyramid_zcml/issues/8

This PR doesn't break anything, so it is safe to merge.

**Comment by bertjwregeer** [comment]
@stevepiercy This will be fixed when https://github.com/Pylons/pyramid_zcml/pull/16 is pulled in.

**Comment by tseaver** [comment]
@stevepiercy can you merge with master and re-push?

**Comment by stevepiercy** [comment]
@tseaver done. The GitHub UI faked me out after I pushed, and I created a duplicate PR #18. The other can be closed after merging one.

**Comment by tseaver** [comment]
Thanks!

**Pull request merged**
